---
 - name: Installing hhtp in remote node
   hosts: localhost
   tasks:
           - name: Install httpd
             ansible.builtin.dnf:
                     name: httpd
                     state: present
             become: yes
