---
 - name: implementing with items
   hosts: 192.168.30.7
   become: yes
   tasks:
   - name: installing packages
     ansible.builtin.dnf:
       name: "{{item}}"
       state: present
     with_items: httpd, firewalld
