---
 - name: Installing hhtp in remote node
   hosts: 192.168.30.7
   tasks:
           - name: Install httpd
             ansible.builtin.dnf:
                     name: httpd
                     state: present
             become: yes
